apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Una release = la base + el contenido de esa versión
resources:
  - ../../base
configMapGenerator:
  - name: hola-html
    files:
      - index.html
