apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cliente-a

# ===== VERSIÓN DE ESTE CLIENTE =====
# Para promover: cambia la release (v1 -> v2), commit y push.
resources:
  - ../../release/v1
configMapGenerator:
  - name: cliente-info
    files:
      - cliente.json
